name: ZulfBungee
main: com.zulfen.zulfbungee.spigot.ZulfBungeeSpigot
version: 0.9.9-pre6
author: zulfen
website: https://github.com/Zulfen/ZulfBungee
description: A Skript addon which adds proxy integration.
api-version: 1.13
depend:
  - Skript
  - ProtocolLib